#ifndef __GAVEL_POWERDEFINE_H
#define __GAVEL_POWERDEFINE_H

#define NUM_DEVICES 5
#define DEBUG_LEDS 6
#define NAME_MAX_LENGTH 15
#define NAME_STRING_LENGTH (NAME_MAX_LENGTH + 1)

#endif // __GAVEL_POWERDEFINE_H